image: node:8

cache:
  paths:
  - node_modules/

stages:
  - deploy

before_script:
  - git config --global user.email "mail@konstantin.io"
  - git config --global user.name "Konstantin Gorodinskiy"

deploy:
  stage: deploy
  script:
   - npm i
   - npm run --silent clean
   - npm run build
   - npm run --silent deploy -- -r https://$TOKEN@github.com/gko/gko.github.io.git
  tags:
    - docker