image: node:8

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
   - npm ci
   - npm run build
   - npm run deploy -- -r https://$TOKEN@github.com/gko/gko.github.io.git
  tags:
    - docker