image: node:8

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:
  before_script:
    - git config --global user.email "mail@konstantin.io"
    - git config --global user.name "Konstantin Gorodinskiy"
  stage: deploy
  script:
   - npm ci
   - npm run deploy
  tags:
    - docker