image: node:8

stages:
  - deploy

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  paths:
  - .npm

before_script:
  - git config --global user.email "mail@konstantin.io"
  - git config --global user.name "Konstantin Gorodinskiy"
  - apt-get update && apt-get -y install -qq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

deploy:
  stage: deploy
  script:
    - npm ci
    - npm run --silent clean
    - npm run build
    - npm run --silent deploy -- -r https://$TOKEN@github.com/gko/gko.github.io.git
  tags:
    - docker